name: graphql_codegen

packages:
  - packages/**
  
scripts:
  analyze:
    run: melos exec -- "dart analyze --fatal-infos ."
  test_dart:
    exec: dart test
    packageFilters:
      flutter: false
      dirExists: "test"
  test_flutter:
    exec: flutter test
    packageFilters:
      flutter: true  
      dirExists: "test"
  build_dart:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      flutter: false
  build_flutter:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      flutter: true
  format:
    exec: dart format

command:
  bootstrap:
    usePubspecOverrides: true