name: graphql_codegen

packages:
  - packages/**
  
scripts:
  analyze: melos exec -- "dart analyze ."
  test_dart: melos exec --ignore=*example* --dir-exists=test -- "dart test"
  test_flutter: melos exec --scope=*example* --dir-exists=test -- "flutter test"
  build_dart:  melos exec --ignore=*example* -- "dart run build_runner build --delete-conflicting-outputs" 
  build_flutter: melos  exec --scope=*example* -- "flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs"
  format: melos exec -- "dart format"
  check: git diff --exit-code
