builders:
  graphql_codegen:
    import: 'package:graphql_codegen/builder.dart'
    builder_factories: ['GraphQLBuilder.builder']
    build_extensions: {'$lib$': ['.graphql.dart']}
    auto_apply: dependents
    build_to: source
    runs_before:
      - json_serializable:json_serializable
